package constants

const (
	STATUS_ACTIVE = 1
	STATUS_STOPPED = 2
	STATUS_DEAD = 3
	STATUS_ERROR = 4
	
	COMMAND_STATUS = 100
	COMMAND_STOP = 101
	COMMAND_START = 102
	COMMAND_RESTART = 103
	COMMAND_KILL = 104
)