package constants

const (
	STATUS_NOT_STARTED = 0
	STATUS_ACTIVE = 1
	STATUS_STOPPED = 2
	STATUS_DEAD = 3
	STATUS_ERROR = 4
	
	COMMAND_STATUS = 100
	COMMAND_STOP = 101
	COMMAND_START = 102
	COMMAND_RESTART = 103
	COMMAND_KILL = 104
	COMMAND_HELP = 105

	ARGUMENT_STATUS_ALL = 200
	ARGUMENT_STATUS_NUMBER = 201

	AUTORESTART_ALWAYS = "Always"
	AUTORESTART_NEVER = "Never"
	AUTORESTART_LIMITED_TIMES = "Limited"
	AUTORESTART_UNEXPECTED_EXITS = "Unexpected exits"

	SIGNAL_SIGTERM = "SIGTERM"
	SIGNAL_SIGINT = "SIGINT"
	SIGNAL_SIGQUIT = "SIGQUIT"

	GREEN    = "\033[32m"
	GREEN_BG = "\033[42;30m"
	YELLOW   = "\033[33m"
	RED      = "\033[31m"
	RED_BG   = "\033[41;30m"
	NO_COLOR = "\033[m"
)